<template src="./tool-bar.html"></template>
<style src="./tool-bar.scss"></style>
<script>
export default {
  name: 'ToolBar',
  data () {
    return {
      optionsDisplay: {
        'useNames': { 'title': " 'names' as identifiers", 'notes': "Use 'names' attribute instead of 'id' attribute. Turn on the option for models with very long or uninformative ids"},
        'correctMathml': { 'title': ' correctons to MathML', 'notes': 'Make some correction for MathML generated by SimBiology. Some of SimBiology models generate wrong MathML. Try this option if something looks wrong in equations.'},
        'equationsOff': { 'title': ' Turn off equations', 'notes': 'Use this option if you are not interested in math. It reduces time of transformation.'}
      },
      waysDisplayPage: [
        'sbml2table',
        'sbml2math'
      ]
    }
  }
}
</script>
